test_color_name_to_hex (__main__.TestExercice) ... ok
test_compute_mse (__main__.TestExercice) ... ok
test_create_list (__main__.TestExercice) ... ERROR
test_list_to_dict (__main__.TestExercice) ... ok

======================================================================
ERROR: test_create_list (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 44, in test_create_list
    output = exercice.create_list()
TypeError: 'list' object is not callable

----------------------------------------------------------------------
Ran 4 tests in 0.001s

FAILED (errors=1)
